// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gpdjxoogukmjlalgufpq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdwZGp4b29ndWttamxhbGd1ZnBxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMTY0ODMsImV4cCI6MjA2ODU5MjQ4M30.Mhus7eGCxZsabzml8A0ghR_C3nQ-eaGx4sALuuw89fU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});