// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdpwzychotnyqshpyerq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkcHd6eWNob3RueXFzaHB5ZXJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMzQ4MTcsImV4cCI6MjA3MDgxMDgxN30.ru5z3fHLhsGUjwi-7RBASjpYjDbQcmDJrk0HB9NBm2I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});