name: Build & Deploy to GitHub Pages

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run build

      - name: Prepare docs folder
        run: |
          rm -rf docs
          mv dist docs
          cp CNAME docs/CNAME 2>/dev/null || true

      - name: Commit and Push docs
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "ci(deploy): update GitHub Pages"
          file_pattern: docs/**
